MANIFEST.in
thunderstorm/__init__.py

Add MANIFEST.in so requirements.txt is included when packaging the library

Add manifest

---

test/test_messaging.py
thunderstorm/__init__.py
thunderstorm/messaging.py

Use the deserialized data as the 'data' property of the TsMessage object passed into a function decorated with the ts_task decorator

Tsmessage fix

---

thunderstorm/__init__.py

This is a dummy release to test out generating the release description.
https://github.com/artsalliancemedia/thunderstorm-library/pull/14#issuecomment-385944825

Dummy release v1.0.1

---

.gitignore
test/test_utils.py
thunderstorm/__init__.py
thunderstorm/schemas.py
thunderstorm/utils.py

Add pagination functionality to the thunderstorm library

[TSA-513] pagination

---

thunderstorm/__init__.py
thunderstorm/messaging.py

This is useful for being able to send a countdown when emiting an event.

WIP: Allow sending of celery options

---

Jenkinsfile
Makefile
docker-compose.yml
requirements-dev.txt
thunderstorm/__init__.py
thunderstorm/schemas.py

Adding some marshmallow schema to share across services for a more common response

[feature] introduce http schema for error

---

test/test_utils.py
thunderstorm/__init__.py
thunderstorm/utils.py

* add paginate function to utils

[release] paginate in v0.1.8

---

Makefile
test/test_flask.py
thunderstorm/__init__.py
thunderstorm/flask.py
thunderstorm/schemas.py

* make `prev_page` and `next_page` on PaginationSchema to be dependant on the request header `TS-Rewritten`
* set defaults on `prev_page` and `next_page`  on PaginationSchema to `None` to achieve a consistent output
* fix rewriting behaviour of `static` type `TS-Rewrittten` header, so that now it passes on the query params

[release] v1.1.9

---

requirements.txt
thunderstorm/__init__.py

Relax celery version requirements so that we pull the newest celery version possible

[feat] relax celery version requirements

---

test/test_messaging.py
thunderstorm/__init__.py
thunderstorm/messaging.py

Adds support for passing task options to the `ts_task` decorator

---

Jenkinsfile
docker-compose.yml
requirements-dev.txt
test/conftest.py
test/fixtures.py
test/flask/test_request_utils.py
test/models.py
thunderstorm/__init__.py
thunderstorm/flask/request_utils.py

Addressing https://github.com/artsalliancemedia/thunderstorm-library/issues/50

Issue/50: ceiling on pagination

---

Jenkinsfile
Makefile
docker-compose.yml
requirements-dev.txt
requirements.txt
setup.py
thunderstorm/kafka_messaging.py
thunderstorm/messaging.py
thunderstorm/shared.py

Add functionality for creating/handling events sent/received via kafka
Drop python 3.5 support

[X-1] kafka messaging

---

thunderstorm/kafka_messaging.py

[fix] use faust_app.monitor for statsd metrics

---

thunderstorm/kafka_messaging.py

[X-1] Performance improvements

---

thunderstorm/kafka_messaging.py

[fix] yield from event_handler

---

thunderstorm/kafka_messaging.py

* Merge faust and kafka-python functionality into single class
* Use event objects on the ts_event decorator

[feat] merge kafka-python and faust functionality, use event objects

---

requirements-dev.txt
test/conftest.py
test/test_kafka_messaging.py
thunderstorm/kafka_messaging.py

[TSA-807](https://artsalliancemedia.atlassian.net/browse/TSA-807)

[TSA-807] TSKafka testing

---

thunderstorm/kafka_messaging.py

Add a `key` parameter to the send_ts_event call to enable key based routing of messages between partitions in kafka. This ensures messages with the same key get routed to the same partition (increases reliability of message ordering)
Test locally with multiple kafka producers and consumers and topics with multiple partitions and everything worked as expected

[feat] use key based partitioning

---

thunderstorm/__init__.py
thunderstorm/kafka_messaging.py

Return None if key is None, else encode as bytes

Key serializer fix

---

test/conftest.py
test/test_kafka_messaging.py
thunderstorm/__init__.py
thunderstorm/kafka_messaging.py
thunderstorm/logging/__init__.py
thunderstorm/logging/celery.py
thunderstorm/logging/flask.py
thunderstorm/logging/kafka.py

Unified logging for kafka(faust)/flask/celery/celery-beat in TS

---

test/conftest.py

[release] re-release v1.5.0

---

thunderstorm/__init__.py
thunderstorm/kafka_messaging.py

[release]using warning instead of warn in logger

---

thunderstorm/__init__.py
thunderstorm/logging/__init__.py
thunderstorm/logging/celery.py
thunderstorm/logging/flask.py

setup root logger for flask & celery

---

setup.py

[release]release v1.5.2

---

thunderstorm/logging/celery.py

[release]fix bug

---

requirements-dev.txt
thunderstorm/__init__.py
thunderstorm/logging/flask.py

get TS_REQUEST_ID beore get g.request_id

---

requirements.txt
test/test_kafka_messaging.py
thunderstorm/__init__.py
thunderstorm/kafka_messaging.py
thunderstorm/logging/__init__.py
thunderstorm/logging/celery.py
thunderstorm/logging/flask.py
thunderstorm/logging/kafka.py

1.add json formatter
2.add trace id for kafka
3.fix duprecated log output

add_json_handler_for_log-add_traceid_for_kafka

---

thunderstorm/__init__.py
thunderstorm/kafka_messaging.py

set max_requst_size default 10M

---

thunderstorm/__init__.py
thunderstorm/logging/celery.py

[release]Fix headers assigned error when celery task retry

---

thunderstorm/__init__.py
thunderstorm/kafka_messaging.py

[release]kafka send error refinement

---

Dockerfile.dev
Makefile
README.md
docker-compose.yml
thunderstorm/__init__.py
thunderstorm/kafka_messaging.py
thunderstorm/logging/__init__.py
thunderstorm/logging/celery.py
thunderstorm/logging/flask.py

Fix/use only one log handler(1.7.0)

---

Jenkinsfile
release-dev.sh
requirements-dev.txt
test/conftest.py
test/flask/test_init_logging.py
thunderstorm/__init__.py
thunderstorm/kafka_messaging.py
thunderstorm/logging/__init__.py
thunderstorm/logging/celery.py
thunderstorm/logging/flask.py

Feature/use only one log handler 1.7.1

---

Jenkinsfile

fix: add thunderstorm.utils __init__.py to fix packge not found

---

requirements-dev.txt

fix version of pytest-asyncio

---

test/flask/test_schema.py
thunderstorm/flask/schemas.py

deserial '' as []

---

thunderstorm/logging/__init__.py

disable logger[data]

---

PULL_REQUEST_TEMPLATE.md
thunderstorm/kafka_messaging.py

@artsalliancemedia/aam-china-ts

feat: update logs

---

PULL_REQUEST_TEMPLATE.md
thunderstorm/__init__.py
thunderstorm/kafka_messaging.py

@artsalliancemedia/aam-china-ts

feat: update kafka consumer metrics key

---

Dockerfile
Jenkinsfile
docker-compose.yml
thunderstorm/logging/__init__.py
thunderstorm/logging/celery.py

@artsalliancemedia/aam-china-ts

feat: logger.propagate set to False

---

test/flask/test_request_utils.py
thunderstorm/flask/request_utils.py

@artsalliancemedia/aam-china-ts
Description
---
* ...

add sync_all_data
